"""kss analyze —— 加载模型并导出特征重要性报告."""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path

import click
import pandas as pd

from kss.models.registry import ModelRegistry

logger = logging.getLogger(__name__)


@click.command()
@click.option(
    "--model",
    "-m",
    "model_name",
    required=True,
    help="ModelRegistry 中的模型名（如 lgb_kcb50_10d）",
)
@click.option("--top", default=20, type=int, help="展示前 N 个最重要的特征")
@click.option(
    "--output",
    "-o",
    default=None,
    help="分析结果输出路径（Markdown），默认 ./storage/reports/analysis_{model}_{date}.md",
    type=click.Path(),
)
@click.pass_context
def cmd(
    ctx: click.Context,
    model_name: str,
    top: int,
    output: str | None,
) -> None:
    """加载指定模型并导出特征重要性 Markdown 报告.

    其它分析维度（最优指标组合、关键价位等）暂未实现，本命令仅产出基于
    LightGBM ``feature_importance(gain)`` 的特征排序。
    """
    today = datetime.now().strftime("%Y%m%d")
    if output is None:
        output = f"./storage/reports/analysis_{model_name}_{today}.md"

    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    registry = ModelRegistry()
    try:
        model = registry.load(model_name)
    except FileNotFoundError as exc:
        click.secho(f"  ❌ {exc}", fg="red")
        ctx.exit(1)
        return

    importance = model.feature_importance()
    if importance is None or importance.empty:
        click.secho("  ❌ 模型未训练或 feature_importance 不可用", fg="red")
        ctx.exit(1)
        return

    importance = importance.head(top)
    output_path.write_text(
        _render_markdown(model_name, importance, today),
        encoding="utf-8",
    )

    click.secho(f"  ✅ 分析完成: {output_path}", fg="green")
    logger.info(
        "Analyze model=%s top=%d output=%s", model_name, top, output_path,
    )


def _render_markdown(model_name: str, importance: pd.DataFrame, date: str) -> str:
    """渲染特征重要性 Markdown 报告."""
    rows = "\n".join(
        f"| {i + 1} | `{row['feature']}` | {row['importance']:.2f} |"
        for i, row in importance.reset_index(drop=True).iterrows()
    )
    return f"""# KSS 模型分析 —— {model_name}

> 生成日期: {date}

## 一、特征重要性（Top {len(importance)}）

| 排名 | 特征 | 重要性 (gain) |
|------|------|---------------|
{rows}

## 二、其它分析

最优指标组合、关键价位、风险位等维度暂未实现；可通过 `kss backtest`
与 `kss predict` 组合获取相关信息。

---

*Generated by KSS analyze*
"""
