#!/usr/bin/env python3
"""log_mv 反向纸交易 — 周报告.

读取过去 N 天的纸交易日志（``storage/paper_trade/*.json``），
计算实际成交收益，对比历史基线 Sharpe 1.74，输出 Markdown 报告 + 可选推送.

部署建议（每周五 17:00 cron，收盘后跑当周）::

    0 17 * * 5 cd /path/to/KSS && python3 scripts/weekly_summary.py --channel all

用法::

    python3 scripts/weekly_summary.py                      # 默认 lookback=7 天
    python3 scripts/weekly_summary.py --lookback 30        # 月度回看
    python3 scripts/weekly_summary.py --channel telegram   # 推送到 Telegram
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

# 复用 paper_trade_log_mv 中的核心函数（避免重复实现）
from scripts.paper_trade_log_mv import (  # noqa: E402
    CHANNEL_CHOICES, _send_notification, summarize_log_dir,
)

BASELINE_SHARPE = 1.74
BASELINE_ANNUAL = 0.801  # 80.1%
DEGRADATION_THRESHOLD = 0.5  # Sharpe < baseline × 50% 触发 alert

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)


def format_weekly_md(summary: dict, lookback: int) -> str:
    """周报告 Markdown."""
    if summary.get("n_days_with_returns", 0) == 0:
        return (
            f"# log_mv 反向 周报告（lookback={lookback}d）\n\n"
            f"⚠️ 当前样本尚无 T+2 实际收益数据可统计。\n"
            f"- n_days_logged: {summary.get('n_days_logged', 0)}\n"
            f"- 提示: 至少需积累 2-3 个交易日后才能算实际成交\n"
        )

    sharpe = summary["sharpe"]
    annual = summary["annualized"]
    max_dd = summary["max_dd"]
    win = summary["win_rate"]
    n = summary["n_days_with_returns"]
    period_start, period_end = summary["sample_period"]

    sharpe_ratio = sharpe / BASELINE_SHARPE if BASELINE_SHARPE > 0 else 0.0
    annual_ratio = annual / BASELINE_ANNUAL if BASELINE_ANNUAL > 0 else 0.0

    if sharpe_ratio < DEGRADATION_THRESHOLD:
        verdict = "🔴 **衰减告警**：实际 Sharpe 远低于历史基线，建议暂停纸交易并审视"
    elif sharpe_ratio < 0.8:
        verdict = "🟡 表现弱于历史基线，需观察"
    elif sharpe_ratio < 1.2:
        verdict = "🟢 表现接近历史基线"
    else:
        verdict = "🟢 表现优于历史基线（注意可能是市场风格倾斜）"

    return "\n".join([
        f"# log_mv 反向 周报告（lookback={lookback}d）",
        "",
        f"**样本期**: {period_start} ~ {period_end}（{n} 个交易日）",
        "",
        "## 当期实际表现",
        "",
        "| 指标 | 当期 | 历史基线 | 比例 |",
        "|------|------|----------|------|",
        f"| Sharpe | {sharpe:.2f} | {BASELINE_SHARPE:.2f} | {sharpe_ratio*100:.0f}% |",
        f"| 年化收益 | {annual*100:+.1f}% | {BASELINE_ANNUAL*100:+.1f}% | {annual_ratio*100:.0f}% |",
        f"| 最大回撤 | {max_dd*100:+.1f}% | -37.1% | — |",
        f"| 胜率 | {win*100:.1f}% | ~55% | — |",
        "",
        f"## 判定",
        "",
        verdict,
        "",
        "## 数据完整度",
        "",
        f"- 累计日志: {summary['n_days_logged']} 天",
        f"- 有 T+2 收益: {n} 天",
        f"- 数据完整率: {n/summary['n_days_logged']*100:.0f}%",
        "",
        "---",
        "_Generated by `scripts/weekly_summary.py`_",
    ])


def main() -> None:
    parser = argparse.ArgumentParser(description="log_mv 反向纸交易周报告")
    parser.add_argument(
        "--lookback", type=int, default=7,
        help="回看天数（默认 7 天）",
    )
    parser.add_argument(
        "--baseline-sharpe", type=float, default=BASELINE_SHARPE,
        help=f"历史基线 Sharpe（默认 {BASELINE_SHARPE}）",
    )
    parser.add_argument(
        "--channel", type=str, default=None, choices=CHANNEL_CHOICES,
        help="推送通道：console / telegram / all",
    )
    parser.add_argument(
        "--alert-on-degradation", action="store_true",
        help="当 Sharpe < baseline × 50%% 时退出码 != 0（cron 可监控）",
    )
    args = parser.parse_args()

    summary = summarize_log_dir(lookback_days=args.lookback)
    md = format_weekly_md(summary, args.lookback)
    print(md)

    # 推送
    if args.channel:
        date_label = summary.get("sample_period", ["?", "?"])[1] if "sample_period" in summary else "?"
        _send_notification(
            message=md, channel=args.channel, title=f"log_mv 周报 {date_label}",
        )

    # 衰减检查
    if args.alert_on_degradation and "sharpe" in summary:
        recent_sharpe = float(summary["sharpe"])
        threshold = args.baseline_sharpe * DEGRADATION_THRESHOLD
        if recent_sharpe < threshold:
            logger.warning(
                "DEGRADATION: Sharpe %.2f < baseline %.2f × %.0f%% = %.2f",
                recent_sharpe, args.baseline_sharpe,
                DEGRADATION_THRESHOLD * 100, threshold,
            )
            sys.exit(2)


if __name__ == "__main__":
    main()
